#ifndef COLORS_H
#define COLORS_H

#define ANSI_COLOR_RESET   "\x1b[0m"
#define ANSI_COLOR_BLACK   "\x1b[30m"
#define ANSI_COLOR_RED     "\x1b[31m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define ANSI_COLOR_YELLOW  "\x1b[33m"
#define ANSI_COLOR_BLUE    "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN    "\x1b[36m"
#define ANSI_COLOR_WHITE   "\x1b[37m"

#define ANSI_COLOR_BRIGHT_BLACK   "\x1b[90m"
#define ANSI_COLOR_BRIGHT_RED     "\x1b[91m"
#define ANSI_COLOR_BRIGHT_GREEN   "\x1b[92m"
#define ANSI_COLOR_BRIGHT_YELLOW  "\x1b[93m"
#define ANSI_COLOR_BRIGHT_BLUE    "\x1b[94m"
#define ANSI_COLOR_BRIGHT_MAGENTA "\x1b[95m"
#define ANSI_COLOR_BRIGHT_CYAN    "\x1b[96m"
#define ANSI_COLOR_BRIGHT_WHITE   "\x1b[97m"

#define COLOR_MAIN ANSI_COLOR_WHITE
#define COLOR_APP  ANSI_COLOR_BRIGHT_GREEN
#define COLOR_TP   ANSI_COLOR_BRIGHT_CYAN
#define COLOR_NW   ANSI_COLOR_BRIGHT_YELLOW
#define COLOR_DL   ANSI_COLOR_BRIGHT_BLUE
#define COLOR_PHY  ANSI_COLOR_BRIGHT_MAGENTA
#define COLOR_ERR  ANSI_COLOR_BRIGHT_RED
#define COLOR_WARN ANSI_COLOR_YELLOW
#define COLOR_WRAP ANSI_COLOR_BRIGHT_BLACK

#endif
